### ISSUE TITLE
Could you inform me more details about the loss function?

### ISSUE THREAD

**Issue by yhao-wang** [abdoelsayed2016/GRG#3]
![image](https://github.com/abdoelsayed2016/GRG/assets/107921246/10b5e8bd-81dd-4b05-8d49-6f0135a45251)
In the denominator, what does "$t_j$" mean, and how are these tokens being filtered? Are they all embeddings from the vocabulary?

**Comment by yhao-wang** [comment]
Or is it the target in the labels?

**Comment by abdoelsayed2016** [comment]
The"$t_j$" in the denominator of the cosine loss function is the target embedding for the j-th token in the sequence. These target embeddings are typically all embeddings from the vocabulary, but they can also be filtered in some way, such as by only including the embeddings for tokens that are likely to be generated by the model.
